### PR TITLE
[FEAT] Added enums to represent API entities

### PR DESCRIPTION
**Pull request by rafapaulin**
# Proposed Changes

Add enums to represent API entities and configs that are defined on Whatsapp Business API just as simple strings

## Contribution type

- [ ] General refactor (changes implementation, but not behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update/improvement

## Related Issue(s)

N/A (PR not related to any tracked issue)

## Motivation, Context and Extra Info

Using simple strings may be a problem to maintainability. Having enums to represent constantly re-used strings not only avoid repetition, but also ease validation and branch selection (switch/case)

### General

- [x] I have read the org's [CONTRIBUTING](https://github.com/42dx/.github/blob/main/CONTRIBUTING.md) file
- [x] All my commit messages follow [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/) standards (we use them to auto-generate the CHANGELOG file :sweat_smile:)
- [x] I confirmed that there aren't any other open PR about the same issue

### Code Standards

- [x] I have performed a self-review of my own code
- [x] Code Lint pass locally with my changes
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

### Documentation and reliability

- [x] My branch is up to date with the project's base branch
- [x] I have made corresponding changes to the documentation
- [x] The documentation changes follow the repository's docs standards
- [x] My changes generate no new warnings

### Testing

- [x] Existing automated tests pass locally with my changes
- [x] I have added new unit/integration tests that prove my fix is effective or that my feature works

## How to verify the changes

1. Run `composer serve`
2. Access the test server at `http://localhost:8000`

## Screenshots (if appropriate)

N/A

### CODE REVIEW

**Comment by rafaelassumpcao** [comment]
I know nothing about PHP. I hope you are having fun 😁

**Comment by rafapaulin** [comment]
@all-contributors please add @rafapaulin for code, design, doc, ideas, infra, maintenance, projectManagement, review, test, tool, tutorial

**Comment by rafapaulin** [comment]
@all-contributors please add @rafapaulin for code, design, doc, ideas, infra, maintenance, projectManagement, review, test, tool, tutorial

**Comment by rafapaulin** [comment]
@all-contributors please add @rafapaulin for code, design, doc, ideas, infra, maintenance, projectManagement, review, test, tool, tutorial

**Comment by rafapaulin** [comment]
@all-contributors please add @rafapaulin for code, design, doc, ideas, infra, maintenance, projectManagement, review, test, tool, tutorial

**Comment by rafapaulin** [comment]
@all-contributors please add @rafapaulin for code, design, doc, ideas, infra, maintenance, projectManagement, review, test, tool, tutorial

**Pull request merged**
